branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: SaltPool
  default_ec2_keyname: null
  default_platform: PHP
  default_region: us-west-2
  profile: eb-cli
  sc: git
